import { brandMaster } from "@prisma/client";

export const newBrandMasterMock: brandMaster = {
  idBrandMaster: 1,
  domain: "",
  brandName: "Upix",
  isActive: true,
  brandLogo: null,
  createdAt: new Date("2024-10-25T19:28:19.000Z"),
  updatedAt: new Date("2024-10-25T19:28:19.000Z"),
  deletedAt: null,
  city: null,
  emailContact: null,
  fieldName: null,
  location: null,
  setorName: null,
  smsContact: null,
  timezone: null,
  placeNumber: null,
  state: null,
  street: null,
  cnpj: null,
  cep: null,
  cityCode: null,
  district: null,
  stripeUserId: null,
  isPoc: false,
  contract: null,
  contractAt: null,
  pocOpenedAt: null,
  manual: null,
  termsOfUse: null,
  privacyPolicy: null,
};
